Fixes androidTest apk crash
 java.lang.NoClassDefFoundError: Failed resolution of: Lkotlin/reflect/jvm/internal/KPropertyImpl;
 	at java.lang.Class.classForName(Native Method)
 	at java.lang.Class.forName(Class.java:454)
 	at androidx.test.internal.runner.TestLoader.doCreateRunner(TestLoader.java:72)
 	at androidx.test.internal.runner.TestLoader.getRunnersFor(TestLoader.java:104)
 	at androidx.test.internal.runner.TestRequestBuilder.build(TestRequestBuilder.java:793)
 	at androidx.test.runner.AndroidJUnitRunner.buildRequest(AndroidJUnitRunner.java:547)
 	at androidx.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:390)
 	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2213)
 Caused by: java.lang.ClassNotFoundException: kotlin.reflect.jvm.internal.KPropertyImpl